### ISSUE TITLE
Adding multiple players in same page

### ISSUE THREAD

**Issue by paishin** [abritopach/capacitor-youtube-player#15]
I am trying to add multiple players in the same window but it seems that each time I call the initialize function the player is changes video instead of creating a new instance.

Can you please share an example of how to add multiple players?

Here is a sample how I am trying to implement this:

```
ngAfterViewInit() {
    this.videos.each((video) => {
          let options = {
            playerId: video.video_id,
            playerSize: {width: '100%', 'min-height': 230},
            videoId: video.video_id,
            playerVars: {autoplay: 1, modestbranding: 1},
            debug: true
          };

          if (Capacitor.platform === 'web')
            this.initializeYoutubePlayerPluginWeb(options);
          else  // Native
            this.initializeYoutubePlayerPluginNative(options);
        });

  async initializeYoutubePlayerPluginWeb(options) {
    const player = await YoutubePlayerWeb.initialize(options);
  }

  async initializeYoutubePlayerPluginNative(options) {
    const { YoutubePlayer } = Plugins;
    const playerReady = await YoutubePlayer.initialize(options);
  }

}
```

**Comment by abritopach** [comment]
Hi @paishin, I'm sorry it took me so long to reply.

I have modified the example (ionic-angular) to load a list of videos.

Although I've uploaded the code to the repository I'll share the [relevant lines](https://github.com/abritopach/capacitor-youtube-player/blob/a6648bbac7019c52a98d2454f310aedb0c608b8b/examples/ionic-test-capacitor-youtube-player/src/app/pages/video-list/video-list.page.ts#L39). 

```
async initializeYoutubePlayerPluginWeb() {
    console.log('HomePage::initializeYoutubePlayerPluginWeb() | method called');

    let options: IPlayerOptions = {playerId: this.videos[0].id, playerSize: {width: 640, height: 360}, videoId: this.videos[0].videoId, fullscreen: true, debug: true};
    const result = await YoutubePlayer.initialize(options);
    console.log('playerReady', result);

    const promisesArray = [];
    this.videos.slice(1).forEach(video => {
      console.log('video', video);
      options = {...options, playerId: video.id, videoId: video.videoId};
      promisesArray.push(YoutubePlayer.initialize(options));
    });

    await Promise.all(promisesArray);
  }
```

You have to load the first video independently so that the player is completely ready and then load the rest of the videos asynchronously. I will take a look at the plugin to find a better solution in the future but for now this solution works.

https://user-images.githubusercontent.com/2934069/143790318-ba21c9aa-2df4-43e2-9b50-f84f90b6ee42.mp4

**Comment by abritopach** [comment]
Added video list example -> [commit ](https://github.com/abritopach/capacitor-youtube-player/commit/82f27c343e60d9b5f890ed8b7200189e52f15c1a)
