### ISSUE TITLE
How to play videos in full screen?

### ISSUE THREAD

**Issue by gassan** [abritopach/capacitor-youtube-player#72]
subj.

**Comment by abritopach** [comment]
Hello! Although I have to update the documentation, I'll share with you how to play the videos in fullscreen mode.

**WEB version | Native version**

When invoking the `YoutubePlayer.initialize` method, it is necessary to pass a new parameter called fullscreen (boolean) so that when the play button is pressed, the video is played in full screen.

**Example**

```
...
const options: IPlayerOptions = {playerId: 'youtube-player', playerSize: {width: 640, height: 360}, videoId: 'tDW2C6rcH6M', fullscreen: true, debug: true};
const result = await YoutubePlayer.initialize(options);
...

```

You can find a complete example at [LINK](https://github.com/abritopach/capacitor-youtube-player/blob/master/examples/ionic-test-capacitor-youtube-player/src/app/home/home.page.ts)

If you have any further questions, let me know.

If you want to contribute to the growth of the plugin, any financial support, no matter how small, is welcome.

https://www.buymeacoffee.com/h6WVj4HcD

**Comment by gassan** [comment]
It does not work for me on IPhone 7 and IPhone Emulator 12 - No matter of fullscreen parameter.

**Comment by abritopach** [comment]
@gassan I have checked and it should be fixed in version [1.0.6](https://github.com/abritopach/capacitor-youtube-player/releases/tag/1.0.6)

**Comment by gassan** [comment]
Ich have checked it and now I have a build problem:

XXX/node_modules/capacitor-youtube-player/ios/Plugin/YPViewController.swift:50:64: Extra argument 'fullscreen' in call

I think default YouTubePlayer must be overridden with yours one, but I have only one (is it default?) located in Pods/Pods/YoutubePlayer and there are no parameter 'fullscreen' at all.

**Comment by abritopach** [comment]
Hello @gassan 

Which version of the plugin are you using?

Have you updated to the latest version (1.0.7)?

**Comment by gassan** [comment]
it was 1.0.6. But have same error with 1.0.7:
<img width="262" alt="Screenshot 2021-11-30 at 09 05 15" src="https://user-images.githubusercontent.com/2382015/144009114-794be9ad-17f5-47e8-b090-d48197a243f1.png">

**Comment by josuelmm** [comment]
Same error.. Any fix
